[package]
name = "another-rust-terminal-app"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.151"

[patch.crates-io]
# libc = { git = "https://github.com/thenotary/libc", branch = "allow-basic-tcgetattr" }
libc = { path = "../../open_source/libc" }
