[package]
name = "thenotary/rust-terminal-app"
version = "0.1.0"
description = "This repo is a POC for validating changes to wasix-org/libc used to target wasix for rust builds"
readme = "./README.md"
repository = "https://github.com/thenotary/poc-another-rust-terminal-app"
homepage = "https://github.com/thenotary/poc-another-rust-terminal-app"
entrypoint = "another-terminal-app"

[[module]]
name = "another-terminal-app"
source = "./target/wasm32-wasmer-wasi/release/app.wasm"

[[command]]
name = "another-terminal-app"
module = "another-terminal-app"
runner = "https://webc.org/runner/wasi"
