[package]
name = "thenotary/rust-terminal-game"
version = '0.1.0'
entrypoint = "another-terminal-game"

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'another-terminal-game'
#source = './target/wasm32-wasip1/debug/rust-terminal-game.wasm'
source = './target/wasm32-wasmer-wasi/release/another-rust-terminal-app.wasm'

[[command]]
name = 'another-terminal-game'
module = 'another-terminal-game'
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "another-terminal-game"
